print('\033[1m' + '', '', '', '', '', '|============================|')
print('\033[1m' + '', '', '', '', '', '|------DERET ARITMATIKA------|')
print('\033[1m' + '', '', '', '', '', '|============================|')
print('\033[0m'+'Masukkan suku pertama')
x = int(input('U1: '))
print('Masukkan suku kedua')
y = int(input('U2: '))
print('Masukkan suku ke-n yang akan dicari')
c = int(input('U ke-n: '))
print('')
beda = int(y-x)
sk = int(x + (c-1)*beda) 
print('Suku pertama = ',x)
print('Beda = ',beda)
print('U',c,' = ',sk,sep='')
print('')
suku = int(c/2*(x+sk))
print('Jumlah',c,'suku pertama = ',suku)
print('\033[1m'+'..........................................')
print('')

print('\033[0m'+'Hasil Deret: ')
for i in range(x,sk+1,beda):
    print(i,' ',end='')
print('\nSelesai.')

exit()
